### ISSUE TITLE
Download CSV not working & CSV Problem when Portal has no Picture

### ISSUE THREAD

**Issue by TechG3n** [Zetaphor/IITC-Ingress-Portal-CSV-Export#2]
Hi,
When i click the 'Download CSV' Button nothing happens.

Also when there is a Portal without a Picture, there should be a Placeholder insteat of nothing (https://commondatastorage.googleapis.com/ingress.com/img/default-portal-image.png)

Firefox 61.0.2 (64-Bit)
IITC 0.26.0.20170108.21732

**Comment by mf-1** [comment]
Check with the lastest file. During my tests the field is empty and should work normally.

**Comment by mvolfik** [comment]
@spammer23 I also experienced the download issue, you can fix it by finding the download function and replacing the link creation and click with just `window.location = 'data:text/csv,[the data]`. Will submit PR on Sunday or Monday, just writing from my phone because I noticed this issue now.

**Comment by Zetaphor** [comment]
@mvolfik Any update on that PR?

**Comment by mvolfik** [comment]
@Zetaphor lol, nothing, completely forgot about it 🤦‍♂️... But I'm off on holiday with just phone and cca 1kbps data speed, so not until Sunday. But setting a reminder this time 🙃

**Comment by mvolfik** [comment]
Well I don't know what changed, but in Firefox 72.0.2 with IITC-CE v0.30.1 everything works fine.

The change is apparently in Firefox, see https://stackoverflow.com/q/32225904/7292139 - it didn't work back in the days, but now it does. I submitted a comment asking for link to some changelog confirming this, will update you if I get response. I think we can close this
