### ISSUE TITLE
Add Uniques visited/captured to Portal CSV Exporter

### ISSUE THREAD

**Issue by D64134n0** [Zetaphor/IITC-Ingress-Portal-CSV-Export#8]
Please add Uniques visited/captured to Portal CSV Exporter

**Comment by Zetaphor** [comment]
As far as I know that data is not available without authenticating with Ingress, which is outside of the scope of this project.

**Comment by D64134n0** [comment]
Thanks for the answer.
Uniques is another plugin that stores info on the user's Google Drive using the Sync plugin. The info is not stored in any ingress server but on the user's Sync plugin data.
I think you already include Keys plugin data. This should be similar.
To even open Intel map you have to authenticate with ingress, so I don't understand your comment.
Anyway I take the chance to thank you for writing this plugin. It is useful as it is. I just was making a suggestion to make it better.
Thanks.

**Comment by Zetaphor** [comment]
Ah gotcha, it's admittedly been many years since I've actually used this, so I'm not actively developing it. However I am always open to pull requests
